export const ROLES = {
  FOUNDER: "FOUNDER",
  BUSINESS_HEAD: "BUSINESS_HEAD",
  STATE_MANAGER: "STATE_MANAGER",
  CITY_MANAGER: "CITY_MANAGER",
  OPERATIONS: "OPERATIONS",
  SUPPORT: "SUPPORT",
  STAFF: "STAFF",
  CUSTOMER: "CUSTOMER",
};

export const ROLE_ACCESS = {
  FOUNDER: ["ALL"],
  BUSINESS_HEAD: ["STATE_MANAGER", "CITY_MANAGER", "OPERATIONS"],
  STATE_MANAGER: ["CITY_MANAGER", "OPERATIONS"],
  CITY_MANAGER: ["OPERATIONS", "STAFF"],
  OPERATIONS: ["STAFF"],
  SUPPORT: ["CUSTOMER"],
};